config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:create, :new, :update, :destroy]
  get '/high_scores' => 'games#index', :as => :high_scores
  get '/games/:id/continue' => 'games#edit', :as => :continue_game

  root 'games#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :player_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:edit, :update, :destroy]

  def index
    @finished_games = Game.where(is_finished: true).order(:final_score).reverse.first(5)
    @unfinished_games = Game.where(:is_finished => [false, nil]).order(:id);
  end

  def new
    @game = Game.new
  end

  def edit
    @game = Game.find(params[:id]);
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to high_scores_path, notice: 'Game was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to high_scores_path, notice: 'Game was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to high_scores_path, notice: 'Game was successfully destroyed.' }
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:aces, :twos, :threes, :fours, :fives, :sixes, :upper_total, :three_of_a_kind,
        :four_of_a_kind, :full_house, :sm_straight, :lg_straight, :yahtzee, :chance, :bonuses, :upper_total, :lower_total,
        :final_score, :is_finished, :player_name, :cross_out_aces, :cross_out_twos, :cross_out_threes, :cross_out_fours,
        :cross_out_fives, :cross_out_sixes, :cross_out_three_of_a_kind, :cross_out_four_of_a_kind, :cross_out_full_house,
        :cross_out_sm_straight, :cross_out_lg_straight, :cross_out_yahtzee, :cross_out_chance)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_dice.html.erb
<div class="yahtzee-dice-container">
  <div class="yahtzee-dice">
    <div class="die die-one" data-die-pos="die-one"></div>
    <div class="die die-two" data-die-pos="die-two"></div>
    <div class="die die-three" data-die-pos="die-three"></div>
    <div class="die die-four" data-die-pos="die-four"></div>
    <div class="die die-five" data-die-pos="die-five"></div>
    <br>
    <%= button_tag 'Roll', type: 'button', name: 'roll-dice' %>
  </div>
</div>

app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="player-name-field text-center">
    <%= f.label :player_name %>
    <%= f.text_field :player_name %>
  </div>

  <table class="form-upper-section">
    <thead>
      <tr>
        <th colspan="2">Upper Section</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.label :aces, "Aces (Total 1's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_aces', class: 'play-button' %>
            <%= f.number_field :aces, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_aces %><%= f.check_box :cross_out_aces, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_aces %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :twos, "Twos (Total 2's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_twos', class: 'play-button' %>
            <%= f.number_field :twos, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_twos %><%= f.check_box :cross_out_twos, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_twos %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :threes, "Threes (Total 3's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_threes', class: 'play-button' %>
            <%= f.number_field :threes, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_threes %><%= f.check_box :cross_out_threes, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_threes %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :fours, "Fours (Total 4's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_fours', class: 'play-button' %>
            <%= f.number_field :fours, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_fours %><%= f.check_box :cross_out_fours, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_fours %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :fives, "Fives (Total 5's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_fives', class: 'play-button' %>
            <%= f.number_field :fives, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_fives %><%= f.check_box :cross_out_fives, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_fives %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :sixes, "Sixes (Total 6's)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_sixes', class: 'play-button' %>
            <%= f.number_field :sixes, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_sixes %><%= f.check_box :cross_out_sixes, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_sixes %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :upper_total %><br/><span class: "score-note">If total is 63 or more, 35 points will be added</span></td>
        <td><%= f.number_field :upper_total, options = { readonly: true } %></td>
      </tr>
    </tbody>
  </table>

  <table class="form-lower-section">
    <thead>
      <tr>
        <th colspan="2">Lower Section</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= f.label :three_of_a_kind, "3 of a kind (Total dice)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_three_of_a_kind', class: 'play-button' %>
            <%= f.number_field :three_of_a_kind, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_three_of_a_kind %><%= f.check_box :cross_out_three_of_a_kind, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_three_of_a_kind %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :four_of_a_kind, "4 of a kind (Total dice)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_four_of_a_kind', class: 'play-button' %>
            <%= f.number_field :four_of_a_kind, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_four_of_a_kind %><%= f.check_box :cross_out_four_of_a_kind, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_four_of_a_kind %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :full_house, "Full House (Score 25)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_full_house', class: 'play-button' %>
            <%= f.number_field :full_house, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_full_house %><%= f.check_box :cross_out_full_house, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_full_house %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :sm_straight, "Small Straight (Score 30)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_sm_straight', class: 'play-button' %>
            <%= f.number_field :sm_straight, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_sm_straight %><%= f.check_box :cross_out_sm_straight, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_sm_straight %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :lg_straight, "Large Straight (Score 40)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_lg_straight', class: 'play-button' %>
            <%= f.number_field :lg_straight, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_lg_straight %><%= f.check_box :cross_out_lg_straight, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_lg_straight %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :yahtzee, "Yahtzee (Score 50)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_yahtzee', class: 'play-button' %>
            <%= f.number_field :yahtzee, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_yahtzee %><%= f.check_box :cross_out_yahtzee, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_yahtzee %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :chance, "Chance (Total dice)" %></td>
        <td>
          <div class="play-container">
            <%= button_tag 'Play', type: 'button', name: 'play_chance', class: 'play-button' %>
            <%= f.number_field :chance, options = { readonly: true, class: 'play-input' } %>
          </div>
          <%= f.label :cross_out_chance %><%= f.check_box :cross_out_chance, options = {class: 'cross-out'} %><%= f.hidden_field :cross_out_chance %></td>
      </tr>
      <tr>
        <td><%= f.label :bonuses, "Bonus Yahtzees (100 each)" %></td>
        <td>
          <%= button_tag 'Play', type: 'button', name: 'play_bonuses', class: 'play-button' %>
          <%= f.number_field :bonuses, options = { readonly: true } %>
        </td>
      </tr>
      <tr>
        <td><%= f.label :lower_total %></td>
        <td><%= f.number_field :lower_total, options = { readonly: true } %></td>
      </tr>
      <tr>
        <td><%= f.label :final_score %></td>
        <td><%= f.number_field :final_score, options = { readonly: true } %></td>
      </tr>
    </tbody>
  </table>

  <%= f.hidden_field :is_finished %>
  <div class="actions">
    <%= f.submit 'Continue Later' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="score-sheet">
  <h1 class="text-center">Yahtzee</h1>

  <%= render 'form', game: @game %>
</div>

<%= render 'dice' %>

<%= link_to 'Back', high_scores_path, class: 'back-link' %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Scores</h1>
<hr/>

<table>
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Score</th>
    </tr>
  </thead>

  <tbody>
    <% @finished_games.each do |game| %>
      <tr>
        <td><%= game.player_name %></td>
        <td><%= game.final_score %></td>
        <td class="no-border"><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Continue Game</h1>
<hr/>
<table>
  <thead>
    <tr>
      <th>Player Name</th>
      <th>Score</th>
      <th>Game ID</th>
    </tr>
  </thead>

  <tbody>
    <% @unfinished_games.each do |game| %>
      <tr>
        <td><%= game.player_name %></td>
        <td><%= game.final_score %></td>
        <td><%= game.id %></td>
        <td class="no-border"><%= link_to 'Continue', continue_game_path(game) %></td>
        <td class="no-border"><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<div class="score-sheet">
  <h1 class="text-center">Yahtzee</h1>

  <%= render 'form', game: @game %>
</div>

<%= render 'dice' %>

<%= link_to 'Back', high_scores_path, class: 'back-link' %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Aces:</strong>
  <%= @game.aces %>
</p>

<p>
  <strong>Twos:</strong>
  <%= @game.twos %>
</p>

<p>
  <strong>Threes:</strong>
  <%= @game.threes %>
</p>

<p>
  <strong>Fours:</strong>
  <%= @game.fours %>
</p>

<p>
  <strong>Fives:</strong>
  <%= @game.fives %>
</p>

<p>
  <strong>Sixes:</strong>
  <%= @game.sixes %>
</p>

<p>
  <strong>Upper total:</strong>
  <%= @game.upper_total %>
</p>

<p>
  <strong>Three of a kind:</strong>
  <%= @game.three_of_a_kind %>
</p>

<p>
  <strong>Four of a kind:</strong>
  <%= @game.four_of_a_kind %>
</p>

<p>
  <strong>Full house:</strong>
  <%= @game.full_house %>
</p>

<p>
  <strong>Sm straight:</strong>
  <%= @game.sm_straight %>
</p>

<p>
  <strong>Lg straight:</strong>
  <%= @game.lg_straight %>
</p>

<p>
  <strong>Yahtzee:</strong>
  <%= @game.yahtzee %>
</p>

<p>
  <strong>Chance:</strong>
  <%= @game.chance %>
</p>

<p>
  <strong>Bonuses:</strong>
  <%= @game.bonuses %>
</p>

<p>
  <strong>Upper total:</strong>
  <%= @game.upper_total %>
</p>

<p>
  <strong>Final score:</strong>
  <%= @game.final_score %>
</p>

<p>
  <strong>Is finished:</strong>
  <%= @game.is_finished %>
</p>

<p>
  <strong>Player name:</strong>
  <%= @game.player_name %>
</p>

<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yahtzee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="yahtzee-app">
      <%= yield %>
    </div>
  </body>
</html>